【東吳大學資管系】資料工程實務與應用<br>
【授課老師】[陳祥輝 (Email : HsiangHui.Chen@gmail.com)](mailto:HsiangHui.Chen@gmail.com)<br>
【facebook】[陳祥輝老師的臉書 (歡迎加好友)](https://goo.gl/osivhx)<br>
【相關課程】[陳祥輝老師的課程]
- [【東吳大學推廣部】](https://www.ext.scu.edu.tw/courses_search.php?key=陳祥輝)
- [【臺北大學推廣教育】](https://dce.ntpu.edu.tw/page-search.php?q=陳祥輝)

【重點提要】
1. 循序結構(Sequential)
2. 選擇結構(Selection) : 
    * if ... elif ... elif ... else 
    * X if C else Y
3. 迭代結構(Iteration) : for / while, break / continue

#### <font color=#0000FF>Python Primitive data types (基本資料型態)</font>

* Numeric Types 
    - int()
    - float()
    - complex()
* bool()
* str()
* None

In [1]:
print(type(10))
print(type(10.))

<class 'int'>
<class 'float'>


In [2]:
x = 10
y = '20'
print(str(x) + y)
print(x + int(y))

1020
30


In [3]:
print(type(float(10)))

<class 'float'>


In [4]:
# 非0:True 0:False

print(bool(10))
print(bool(-10))
print(bool(0))

True
True
False


In [5]:
print(int(True))
print(int(False))

1
0


In [6]:
sum([True, True, False, False, True])

3

### <font color=#0000FF>【比較以下不同import用法的差異】</font>
* import numpy as np
* import numpy.random as rnd1
* from numpy import random as rnd2
* from numpy.random import random

<table>
<tr><td>
<img src='http://180.218.162.136:2018/Images/Python/importDiag.png' width=300 height=300 alt="這裡是放一張 importDiag.png 的示意圖"></td><td>
<img src='http://180.218.162.136:2018/Images/Python/importNumpy.png' width=300 height=300 alt="這裡是放一張 importNumpy.png 的示意圖">
</td></tr>
</table>

In [7]:
!conda env list

# conda environments:
#
                         C:\Anaconda3
base                  *  C:\Users\sandy\.conda\envs\Py39
tf2                      C:\Users\sandy\.conda\envs\tf2



### <font color=#0000FF>1.各種的import方式</font>

#### 【方法一】

In [12]:
import numpy as np
import math

In [13]:
np

<module 'numpy' from 'C:\\Users\\sandy\\.conda\\envs\\Py39\\lib\\site-packages\\numpy\\__init__.py'>

In [14]:
math

<module 'math' (built-in)>

In [28]:
# 套件:numpy，子套件:random，方法:random
print(np.random.random())

0.5513147690828912


In [27]:
# 設定 seed 每次抽出來都一樣，數字沒有意義，效果不好就換一個，設定一次用一次，離開這個cell就沒了
np.random.seed(123)
print(np.random.random())
print(np.random.random())
print(np.random.random())

0.6964691855978616
0.28613933495037946
0.2268514535642031


#### 【方法二】

In [29]:
import numpy.random as rnd1
from numpy import random as rnd2

In [30]:
print(rnd1.random())
print(rnd2.random())

0.7194689697855631
0.42310646012446096


#### 【方法三】要小心使用，避免覆蓋掉內建函數

In [32]:
from numpy.random import random     # 如果內建函數有random會被蓋掉
from numpy.random import *          # 特別小心使用，除非很熟，不然不曉得有哪些函數會被蓋掉

In [33]:
random()

0.9807641983846155

#### 【常用的隨機產生亂數】

In [35]:
# 含起不含迄[0.0, 1.0) >=0 <1
print(np.random.random())
print(np.random.random(1)[0])
print(np.random.random(5))          # 會變 list

0.3980442553304314
0.7379954057320357
[0.18249173 0.17545176 0.53155137 0.53182759 0.63440096]


In [37]:
print(np.random.randn(3, 4))      # 標準常態分配，99.7%會落在-3 ~ 3

[[ 0.72491523  1.49582653  0.74658059 -1.10098526]
 [-1.4103012  -0.74765132 -0.98486761 -0.74856868]
 [ 0.24036728 -1.85563747 -1.7794548  -2.75022426]]


In [39]:
# 要一刀切下去，分成左右，左位子參數、右關鍵參數，不能關鍵參數在位子參數的左邊

print(np.random.randint(11, 20+1))
print(np.random.randint(low=11, high=20+1, size=1))

15
[17]


In [40]:
print(np.random.choice(a=[1,2,3,4,5,6]))
print(np.random.choice(a=[1,2,3,4,5,6], size=1))
print(np.random.choice(a=[1,2,3,4,5,6], size=7, replace=True))    # replace取出要不要放回，true重複抽
print(np.random.choice(a=[1,2,3,4,5,6], size=7, replace=False))

6
[4]
[3 1 5 4 2 4 3]


ValueError: Cannot take a larger sample than population when 'replace=False'

In [44]:
print(np.random.choice(a=[1,2,3,4,5,6], 
                       size=7, 
                       replace=True,
                       p=[2/8, 2/8, 1/8, 1/8, 1/8, 1/8]))    # p是機率

[1 3 1 6 4 4 1]


#### restart kernel

In [1]:
# -*- coding: utf-8 -*-
from platform import python_version
import os, time, socket
import numpy as np

print("【日期時間】{}".format(time.strftime("%Y/%m/%d %H:%M:%S")))
print("【工作目錄】{}".format(os.getcwd()))
print("【主機名稱】{} ({})".format(socket.gethostname(),socket.gethostbyname(socket.gethostname())))
print("【Python】{}".format(python_version()))

%autosave 120

【日期時間】2022/10/05 14:13:50
【工作目錄】C:\資料工程
【主機名稱】LAPTOP-HN8S2UQE (192.168.1.107)
【Python】3.9.12


Autosaving every 120 seconds


### <font color=#0000FF>2.選擇結構(Selection)</font>

In [2]:
usr = input('請輸入一個數值')
print(type(usr))

請輸入一個數值20
<class 'str'>


In [3]:
usr = input('請輸入一個數值')
usr = int(usr)
print(type(usr))

請輸入一個數值20
<class 'int'>


In [4]:
rnd = np.random.randint(0, 100+1)

if rnd >= 50 :
    print(f'rnd = {rnd}, 大於等於50')

In [6]:
rnd = np.random.randint(0, 100+1)

if rnd >= 50 :                           # :是一個區塊，內縮4格是必要
    print(f'rnd = {rnd}, 大於等於50')    
    print(f'rnd = {rnd}, 大於等於50')    
    print(f'rnd = {rnd}, 大於等於50')    
else :
    print(f'rnd = {rnd}, 小於50')
    print(f'rnd = {rnd}, 小於50')
    print(f'rnd = {rnd}, 小於50')

rnd = 17, 小於50
rnd = 17, 小於50
rnd = 17, 小於50


<font color=#0000FF>
if ... elif ... elif ... else ...
</font>

- 電腦亂數產生 : 0 - 100之間
- 等於亂數 : 答對
- 距離亂數小於等於 5 : 接近
- 距離亂數大於 5 : 太大
- 距離亂數小於 -5 : 太小

In [7]:
rnd = np.random.randint(0,100+1)

usrrnd = np.random.randint(0, 100+1)
print(f'rnd : {rnd}')

usr = int(input('請輸入介於0-100之間的數 : '))

if usr == rnd :
    print('答對')
elif abs(usr - rnd) <= 5 :
    print('接近')
elif usr - rnd > 5 :
    print('太大')
else :
    print('太小')

rnd : 6
請輸入介於0-100之間的數 : 10
接近


In [8]:
min_ = 0 ; max_ = 200       # 因為 min, max是保留字，所以加底線，這樣要改比較方便

rnd = np.random.randint(min_, max_+1)
print(f'rnd : {rnd}')

usr = int(input(f'請輸入介於{min_}-{max_}之間的數 : '))

if usr == rnd :
    print('答對')
elif abs(usr - rnd) <= 5 :
    print('將近')
elif usr - rnd > 5 :
    print('太大')
else :
    print('太小')

rnd : 52
請輸入介於0-200之間的數 : 100
太大


<font color=#0000FF>
X if Condition else Y
</font>

In [9]:
score = np.random.randint(0, 100+1)
print(f'score : {score}')

if score >= 60 :
    print('及格')
else :
    print('不及格')

score : 24
不及格


In [10]:
score = np.random.randint(0, 100+1)
print(f'score : {score}')

print('及格' if score >= 60 else '不及格')

score : 49
不及格


In [21]:
score = np.random.randint(0, 100+1)
print(f"score : {score} \n狀態 : {'及格' if score >= 60 else '不及格'}")    # 引號太多，外面""，裡面''

score : 76 
狀態 : 及格


### <font color=#0000FF>3.迭代結構(Iteration)</font>

#### <font color=#0000FF>比較 range(), np.arange(), np.linspace()</font>

In [1]:
import numpy as np

#### range(stop) -> range object
- range(start, stop[, step]) -> range object
- Return an object that produces a sequence of <font color=#FF0000>integers</font> from start (inclusive) to stop (exclusive) by step.


In [22]:
# 【重點】只能用於整數
print(list(range(10)))
print(list(range(11, 20+1)))
print(list(range(11, 20+1, 2)))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
[11, 13, 15, 17, 19]


#### np.arange([start,] stop[, step,], dtype=None) 
- Return evenly spaced values within a given interval.

- [note]
    - stop : number
    - End of interval.  The interval does not include this value.


In [23]:
# 【重點】可以用於浮點數
print(np.arange(10.5))
print(np.arange(11, 20.5))
print(np.arange(11, 20.5, 2.5))

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[11. 12. 13. 14. 15. 16. 17. 18. 19. 20.]
[11.  13.5 16.  18.5]


#### np.linspace(start, stop, num=50, <font color=#FF0000>endpoint=True</font>, retstep=False, dtype=None)
- Return evenly spaced numbers over a specified interval.
- [note]
    - stop : scalar
    - The end value of the sequence, unless `endpoint` is set to False.
- [examples]    
    - np.linspace(start=1,stop=11,num=10)
    - np.linspace(start=1,stop=11,num=10,dtype=int)
    - np.linspace(start=1,stop=11,num=10,retstep=True,dtype=int)
    - np.linspace(start=1,stop=11,num=10,endpoint=False,retstep=True)

In [24]:
# 少數的含起也含迄，num是要等距離取幾個點，endpoint是要不要含迄，retstep距離多少

print(np.linspace(0, 10, 3, endpoint=True))
print(np.linspace(0, 10, 3, endpoint=False))
print(np.linspace(0, 10, 3, endpoint=True, retstep=True)) # return step

[ 0.  5. 10.]
[0.         3.33333333 6.66666667]
(array([ 0.,  5., 10.]), 5.0)


In [25]:
data, step = np.linspace(0, 10, 3, endpoint=True, retstep=True)    # tuple
print(data)
print(step)

[ 0.  5. 10.]
5.0


In [26]:
(data, step) = np.linspace(0, 10, 3, endpoint=True, retstep=True)
print(data)
print(step)

[ 0.  5. 10.]
5.0


#### <font color=#0000FF>for range 的使用(一)</font>

In [1]:
for i in range(5) :
    print(i)

0
1
2
3
4


In [3]:
for _ in range(5) :               # 匿名變數_，變數不重要，不用回傳
    print("*", end='\t')

*	*	*	*	*	

In [8]:
for i in range(1, 9+1) :
    print(i)

1
2
3
4
5
6
7
8
9


In [9]:
for i in range(1, 9+1) :
    for j in range(1, 6+1) :
        print(i)
    print()

1
1
1
1
1
1

2
2
2
2
2
2

3
3
3
3
3
3

4
4
4
4
4
4

5
5
5
5
5
5

6
6
6
6
6
6

7
7
7
7
7
7

8
8
8
8
8
8

9
9
9
9
9
9



In [7]:
for i in range(1, 9+1) :          # interval區間迴圈
    for j in range(1, 6+1) :
        print(f'{i:>2d} * {j:>2d} = {i*j:>2d}')
    print()

 1 *  1 =  1
 1 *  2 =  2
 1 *  3 =  3
 1 *  4 =  4
 1 *  5 =  5
 1 *  6 =  6

 2 *  1 =  2
 2 *  2 =  4
 2 *  3 =  6
 2 *  4 =  8
 2 *  5 = 10
 2 *  6 = 12

 3 *  1 =  3
 3 *  2 =  6
 3 *  3 =  9
 3 *  4 = 12
 3 *  5 = 15
 3 *  6 = 18

 4 *  1 =  4
 4 *  2 =  8
 4 *  3 = 12
 4 *  4 = 16
 4 *  5 = 20
 4 *  6 = 24

 5 *  1 =  5
 5 *  2 = 10
 5 *  3 = 15
 5 *  4 = 20
 5 *  5 = 25
 5 *  6 = 30

 6 *  1 =  6
 6 *  2 = 12
 6 *  3 = 18
 6 *  4 = 24
 6 *  5 = 30
 6 *  6 = 36

 7 *  1 =  7
 7 *  2 = 14
 7 *  3 = 21
 7 *  4 = 28
 7 *  5 = 35
 7 *  6 = 42

 8 *  1 =  8
 8 *  2 = 16
 8 *  3 = 24
 8 *  4 = 32
 8 *  5 = 40
 8 *  6 = 48

 9 *  1 =  9
 9 *  2 = 18
 9 *  3 = 27
 9 *  4 = 36
 9 *  5 = 45
 9 *  6 = 54



#### <font color=#0000FF>foreach 的使用(二)</font>

In [15]:
import string

In [11]:
print(string.ascii_letters)
print(string.ascii_lowercase)
print(string.ascii_uppercase)
print(string.digits)
print(string.printable)
print(string.punctuation)

abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ
abcdefghijklmnopqrstuvwxyz
ABCDEFGHIJKLMNOPQRSTUVWXYZ
0123456789
0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~ 	

!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [12]:
print(string.ascii_lowercase[:10])

abcdefghij


In [27]:
print(list(string.ascii_lowercase))
print(tuple(string.ascii_lowercase))
print(set(string.ascii_lowercase))

['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z']
('a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z')
{'u', 'r', 'k', 'w', 'n', 'l', 'c', 'd', 'b', 'e', 's', 'g', 'h', 'a', 'z', 'q', 'm', 'p', 'j', 'v', 'f', 'x', 'y', 't', 'i', 'o'}


In [16]:
for w in string.ascii_letters[:10]:
    print(w, end='\t')

a	b	c	d	e	f	g	h	i	j	

In [17]:
'123a'.isdigit()

False

In [22]:
# 分割
'a|b|c|d|資|管|系'.split('|')

['a', 'b', 'c', 'd', '資', '管', '系']

In [20]:
# 合併
lst = ['aa', 'bb', 'cc']
print(''.join(lst))
print('|'.join(lst))

aabbcc
aa|bb|cc


In [21]:
lst = ['aa', 'bb', 'cc']
for f in lst :
    print(f)

aa
bb
cc


#### <font color=#0000FF>for與 dict 的使用(三)</font>

In [24]:
d1 = {'a':100, 'b':200, 'c':300}
print(d1.items())
print(len(d1))

print('------------------------')

for k, v in d1.items() :
    print(f'key : {k}, value : {v}')

dict_items([('a', 100), ('b', 200), ('c', 300)])
3
------------------------
key : a, value : 100
key : b, value : 200
key : c, value : 300


In [25]:
d1 = {'a':100, 'b':200, 'c':300}
for item in d1.items() :
    print(f'data : {item}')

data : ('a', 100)
data : ('b', 200)
data : ('c', 300)


In [28]:
d1 = {'a':100, 'b':200, 'c':300}
for item in d1.items() :
    print(f'key : {item[0]}, value : {item[1]}')

key : a, value : 100
key : b, value : 200
key : c, value : 300


#### <font color=#0000FF>for 與 [ ] 的結合</font>

計算 $\sum_{x=1}^{x=20} x^2$

In [1]:
total = 0
for x in range(1, 20+1) :
    total = total + x**2
print(total)

2870


In [2]:
print([x for x in range(1, 20+1)])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]


In [3]:
print([x**2 for x in range(1, 20+1)])

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400]


In [4]:
print(sum([x**2 for x in range(1, 20+1)]))

2870


計算 $\sum_{x=1}^{x=20} x^2$  when x is odd

In [5]:
total = 0
for x in range(1, 20+1) :
    if x%2 == 1 :
        total = total + x**2
print(total)

1330


In [6]:
[x for x in range(1, 20+1)]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [7]:
[x for x in range(1, 20+1) if x%2==1]    # 條件篩選沒有else，只挑要的

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19]

In [11]:
[x**2 for x in range(1, 20+1) if x%2==1]

[1, 9, 25, 49, 81, 121, 169, 225, 289, 361]

In [9]:
sum([x**2 for x in range(1, 20+1) if x%2==1])

1330

### 將以下的資料進行轉換
- lst = [0, 0, 0, 1, 1, 0, 1, 2]
    - 0 : 女生
    - 1 : 男生

In [12]:
lst = [0, 0, 0, 1, 1, 0, 1, 2]
print([x for x in lst])

[0, 0, 0, 1, 1, 0, 1, 2]


In [13]:
lst = [0, 0, 0, 1, 1, 0, 1]
print([x for x in lst if x in [0, 1]])

[0, 0, 0, 1, 1, 0, 1]


In [14]:
lst = [0, 0, 0, 1, 1, 0, 1]
print(['女生' if x==0 else '男生' for x in lst if x in [0, 1]])

['女生', '女生', '女生', '男生', '男生', '女生', '男生']


#### <font color=#0000FF>for 與 { } 的結合</font>

### 請使用 dict 列出26個字母當key，所在位置當 value
- {'a':1, 'b':2, 'c':3, ..........., 'z':26}

In [16]:
d = {}
idx = 1
for w in string.ascii_lowercase :
    d[w] = idx
    idx += 1
    
print(d.items())

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7), ('h', 8), ('i', 9), ('j', 10), ('k', 11), ('l', 12), ('m', 13), ('n', 14), ('o', 15), ('p', 16), ('q', 17), ('r', 18), ('s', 19), ('t', 20), ('u', 21), ('v', 22), ('w', 23), ('x', 24), ('y', 25), ('z', 26)])


In [5]:
d = dict()
for idx, w in enumerate(string.ascii_letters, start=1) :
    d[w] = idx

print(d.items())

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7), ('h', 8), ('i', 9), ('j', 10), ('k', 11), ('l', 12), ('m', 13), ('n', 14), ('o', 15), ('p', 16), ('q', 17), ('r', 18), ('s', 19), ('t', 20), ('u', 21), ('v', 22), ('w', 23), ('x', 24), ('y', 25), ('z', 26), ('A', 27), ('B', 28), ('C', 29), ('D', 30), ('E', 31), ('F', 32), ('G', 33), ('H', 34), ('I', 35), ('J', 36), ('K', 37), ('L', 38), ('M', 39), ('N', 40), ('O', 41), ('P', 42), ('Q', 43), ('R', 44), ('S', 45), ('T', 46), ('U', 47), ('V', 48), ('W', 49), ('X', 50), ('Y', 51), ('Z', 52)])


In [18]:
d = {k:v for v, k in enumerate(string.ascii_lowercase, start=1)}
print(d.items())

dict_items([('a', 1), ('b', 2), ('c', 3), ('d', 4), ('e', 5), ('f', 6), ('g', 7), ('h', 8), ('i', 9), ('j', 10), ('k', 11), ('l', 12), ('m', 13), ('n', 14), ('o', 15), ('p', 16), ('q', 17), ('r', 18), ('s', 19), ('t', 20), ('u', 21), ('v', 22), ('w', 23), ('x', 24), ('y', 25), ('z', 26)])


### 計算每一個字出現的頻率，並排除掉不要的字

In [21]:
txt = """
兩岸情勢嚴峻，兵役確定延長1年役期，國防部長邱國正今天在立法院表示，
國防部朝年底前公告義務役期延長的方向努力。邱國正答詢時並說明，
役男服完軍事訓練役4個月，不會因役期延長1年再回營。

國防部長邱國正說，服軍事訓練役4個月役男不會因役期延長1年再回營。（中央社＼檔案照）
邱國正上午列席立法院外交及國防委員會專案報告並備詢。國民黨立委江啟臣質詢關切，
若義務役恢復為1年，現階段服4個月軍事訓練役的役男領的是「結訓令」而非「退伍令」
，民眾擔憂服軍事訓練役的役男屆時是否要再回營補實其餘8個月役期。邱國正答詢說「不會影響」，
國防部對於義務役期延長的議題戒慎恐懼，民眾擔憂、國防部也很擔憂。

邱國正在會前受訪也針對是否在今年底前公告義務役期將延長說明，依規定若義務役期延長要公告1年
後實施，若今年底前公告，公告滿1年後可在113年實施；但若是明年（112年）公告，得再經過1年，
也就是114年才能實施，雖然他不能承諾時程，但期望今年底前公告，國防部也朝這方向努力。
"""

In [22]:
"aabd".count('a')

2

In [23]:
# 轉成set讓文字不要重複
d = {w:txt.count(w) for w in set(txt)}
print(d.items())

dict_items([('但', 2), ('規', 1), ('關', 1), ('列', 1), ('天', 1), ('領', 1), ('受', 1), ('長', 9), ('段', 1), ('服', 4), ('力', 2), ('社', 1), ('檔', 1), ('及', 1), ('江', 1), ('男', 4), ('於', 1), ('在', 4), ('質', 1), ('岸', 1), ('報', 1), ('否', 2), ('實', 4), ('3', 1), ('響', 1), ('法', 2), ('前', 5), ('訪', 1), ('示', 1), ('能', 2), ('8', 1), ('席', 1), ('切', 1), ('向', 2), ('底', 4), ('；', 1), ('。', 7), ('確', 1), ('勢', 1), ('題', 1), ('他', 1), ('承', 1), ('眾', 2), ('結', 1), ('1', 13), ('訓', 5), ('恢', 1), ('＼', 1), ('對', 2), ('施', 3), ('補', 1), ('委', 2), ('外', 1), ('因', 2), ('今', 4), ('案', 2), ('為', 1), ('就', 1), ('延', 7), ('上', 1), ('防', 7), ('定', 2), ('4', 4), ('黨', 1), ('義', 5), ('不', 4), ('兵', 1), ('員', 1), ('針', 1), ('「', 3), ('練', 4), ('午', 1), ('嚴', 1), ('務', 5), ('得', 1), ('詢', 4), ('年', 15), ('再', 4), ('2', 1), ('交', 1), ('懼', 1), ('若', 4), ('期', 9), ('才', 1), ('並', 2), ('朝', 2), ('軍', 4), ('\n', 14), ('會', 5), ('屆', 1), ('方', 2), ('營', 3), ('情', 1), ('公', 7), ('央', 1), ('雖', 1), ('答', 2), ('明', 3), ('依'

In [30]:
# \連結符號，後面一個空格都不可以有
stop_words = ['（', '）', '＼', '「', '」', '\n', '；', '，', '、', '。'] + \
            list(string.ascii_letters) + \
            list(string.digits)
d = {w:txt.count(w) for w in set(txt) if w not in stop_words}
print(d.items())

dict_items([('但', 2), ('規', 1), ('關', 1), ('列', 1), ('天', 1), ('領', 1), ('受', 1), ('長', 9), ('段', 1), ('服', 4), ('力', 2), ('社', 1), ('檔', 1), ('及', 1), ('江', 1), ('男', 4), ('於', 1), ('在', 4), ('質', 1), ('岸', 1), ('報', 1), ('否', 2), ('實', 4), ('響', 1), ('法', 2), ('前', 5), ('訪', 1), ('示', 1), ('能', 2), ('席', 1), ('切', 1), ('向', 2), ('底', 4), ('確', 1), ('勢', 1), ('題', 1), ('他', 1), ('承', 1), ('眾', 2), ('結', 1), ('訓', 5), ('恢', 1), ('對', 2), ('施', 3), ('補', 1), ('委', 2), ('外', 1), ('因', 2), ('今', 4), ('案', 2), ('為', 1), ('就', 1), ('延', 7), ('上', 1), ('防', 7), ('定', 2), ('黨', 1), ('義', 5), ('不', 4), ('兵', 1), ('員', 1), ('針', 1), ('練', 4), ('午', 1), ('嚴', 1), ('務', 5), ('得', 1), ('詢', 4), ('年', 15), ('再', 4), ('交', 1), ('懼', 1), ('若', 4), ('期', 9), ('才', 1), ('並', 2), ('朝', 2), ('軍', 4), ('會', 5), ('屆', 1), ('方', 2), ('營', 3), ('情', 1), ('公', 7), ('央', 1), ('雖', 1), ('答', 2), ('明', 3), ('依', 1), ('正', 6), ('是', 5), ('可', 1), ('也', 4), ('令', 2), ('程', 1), ('中', 1), ('過', 1), ('影', 1), ('要', 2

### 具名函數與匿名函數

In [32]:
def add(x, y) :
    return x + y

In [33]:
add(3, 4)

7

In [34]:
(lambda x, y : x + y)(3, 5)

8

### 如果在參數列中出現 /, *
- / : 左邊的參數一定要採用位置參數(positional argument)
* \* : 右邊的參數一定要採用關鍵參數(keyword argument)
---
- 位置參數(positional argument) : 不帶參數名稱
    - 例如 : add(3, 4)
- 關鍵參數(keyword argument) : 帶參數名稱
    - 例如 : add(x=3, y=4)
---
- 【重點】: 位置參數(positional argument)一定要在左，關鍵參數(keyword argument)一定要在右

### 計算每一個字出現的頻率，並排除掉不要的字，並取出出現頻率最高的前10個字


In [36]:
sorted(d.items(), key=lambda x : x[1], reverse=True)[:10]    # lambda 決定用 key:[0] 還是 value:[1] 排序
                                                             # reverse True:遞減  False:遞增

[('役', 18),
 ('年', 15),
 ('國', 14),
 ('長', 9),
 ('期', 9),
 ('告', 8),
 ('延', 7),
 ('防', 7),
 ('公', 7),
 ('正', 6)]

In [37]:
d.items()

dict_items([('但', 2), ('規', 1), ('關', 1), ('列', 1), ('天', 1), ('領', 1), ('受', 1), ('長', 9), ('段', 1), ('服', 4), ('力', 2), ('社', 1), ('檔', 1), ('及', 1), ('江', 1), ('男', 4), ('於', 1), ('在', 4), ('質', 1), ('岸', 1), ('報', 1), ('否', 2), ('實', 4), ('響', 1), ('法', 2), ('前', 5), ('訪', 1), ('示', 1), ('能', 2), ('席', 1), ('切', 1), ('向', 2), ('底', 4), ('確', 1), ('勢', 1), ('題', 1), ('他', 1), ('承', 1), ('眾', 2), ('結', 1), ('訓', 5), ('恢', 1), ('對', 2), ('施', 3), ('補', 1), ('委', 2), ('外', 1), ('因', 2), ('今', 4), ('案', 2), ('為', 1), ('就', 1), ('延', 7), ('上', 1), ('防', 7), ('定', 2), ('黨', 1), ('義', 5), ('不', 4), ('兵', 1), ('員', 1), ('針', 1), ('練', 4), ('午', 1), ('嚴', 1), ('務', 5), ('得', 1), ('詢', 4), ('年', 15), ('再', 4), ('交', 1), ('懼', 1), ('若', 4), ('期', 9), ('才', 1), ('並', 2), ('朝', 2), ('軍', 4), ('會', 5), ('屆', 1), ('方', 2), ('營', 3), ('情', 1), ('公', 7), ('央', 1), ('雖', 1), ('答', 2), ('明', 3), ('依', 1), ('正', 6), ('是', 5), ('可', 1), ('也', 4), ('令', 2), ('程', 1), ('中', 1), ('過', 1), ('影', 1), ('要', 2

#### <font color=#0000FF>撰寫一個 質數 的判斷程式</font>
迴圈種類
- for 迴圈
- while 迴圈

跳躍指令

- break : 直接跳離迴圈外
- continue : 跳至迴圈開始處繼續往下一次執行

- <img src='http://180.218.162.136:2018/Images/Python/break_and_continue.jpg' width=300 align=left></img>

In [40]:
num = 11
isPrimeFlag = True
for f in range(2, num) :
    if num%f == 0 :
        isPrimeFlag = False
        break

print(isPrimeFlag)

True


#### <font color=blue>function</font>
- <img src='http://180.218.162.136:2018/Images/Python/function.jpg' width=500 align=left></img>

In [44]:
def isPrime(num) :
    isPrimeFlag = True
    for f in range(2, num) :          # 知道跑幾次用 for
        if num%f == 0 :
            isPrimeFlag = False
            break

    return isPrimeFlag

In [46]:
print(isPrime(13))
print(isPrime(121))

True
False


In [76]:
def isPrime(num) :
    isPrimeFlag = True
    f = 2
    while isPrimeFlag and f < num:        # 一個狀態用 while
        if num%f == 0 :
            isPrimeFlag = False
#             break
        f += 1
    return isPrimeFlag

In [71]:
print(isPrime(132))
print(isPrime(11))

False
True
